CREATE TABLE reservations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  mac VARCHAR(17) NOT NULL UNIQUE,
  ip VARCHAR(15) NOT NULL,
  device_name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
